version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --default-artifact-root /mlflow/artifacts
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    user: "0:0"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - PYTHONPATH=/opt/airflow/src
      - _PIP_ADDITIONAL_REQUIREMENTS=pymongo requests pandas scikit-learn mlflow python-dotenv
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Iqbal --lastname Ahsan --role Admin --email iqbalahsan4470@gmail.com && airflow webserver & airflow scheduler"
    depends_on:
      - mongo
      - mlflow
    restart: unless-stopped

volumes:
  mongo_data:
  mlflow_data: